title: PyNeut — Python Neutronics
description: Continuous-energy Monte Carlo neutron transport, validated against OpenMC
theme: jekyll-theme-cayman

# GitHub metadata
repository: ybadr16/PyNeut
# plugins
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index

# Enable relative links
relative_links:
  enabled: true
  collections: false

# Enable README index
readme_index:
  enabled: true

# Exclude from processing
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules